# Generated by Django 4.1.7 on 2023-02-24 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_usernet_bio_usernet_birthday_usernet_gender_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usernet',
            old_name='git_hub',
            new_name='github',
        ),
        migrations.AlterField(
            model_name='usernet',
            name='first_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usernet',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], default='male', max_length=6),
        ),
    ]
