version: '3.7'

services:
  mfsn:
    build:
      dockerfile: Dockerfile
      context: ./
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
  localhost-db:
    image: postgres:12
    volumes:
      - mfsn_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev
    ports:
      - 5433:5433

volumes:
  mfsn_data: